version: 0.0.{build}
os:
  - Visual Studio 2012
clone_depth: 1
skip_tags: true
clone_folder: c:\projects\openigtlink
configuration:
  - Release
platform:
  - x64
before_build:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: echo Running cmake...
  - cmd: SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - cmd: SET P=c:\projects\openigtlink
  - cmd: set TBB_INSTALL_DIR=%P%/tbb
  - cmd: set TBB_ARCH_PLATFORM=intel64/vc14
  - cmd: cmake -G"Visual Studio 14 2015 Win64" ..
build_script:
  - cmd: msbuild /clp:Verbosity=minimal /nologo OpenIGTLink.sln
after_build:
  - cmd: cd ..
  - cmd: mkdir TestBuild
  - cmd: cd TestBuild
  - cmd: cmake -G"Visual Studio 14 2015 Win64" ..\Testing
  - cmd: msbuild /clp:Verbosity=minimal /nologo OpenIGTLinkTesting.sln
  - cmd: msbuild RUN_TESTS.vcxproj
  